name: Deploy Jupyter Book to GitHub Pages

on:
  push:
    branches:
      - main  # 🚨 change to your default branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11  # or your preferred version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/book/requirements.txt
          pip install jupyter-book

      - name: Build the Jupyter Book
        run: |
          jupyter-book build docs/book/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/book/_build/html
          publish_branch: gh-pages
